-- 1. Payments Table
CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id TEXT UNIQUE NOT NULL,
    payer_email TEXT,
    payer_id TEXT,
    roblox_username TEXT,
    roblox_uaid TEXT,
    tier TEXT,
    amount NUMERIC,
    currency TEXT,
    payment_status TEXT,
    generated_keys TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tickets Table
CREATE TABLE IF NOT EXISTS tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_number TEXT UNIQUE NOT NULL,
    user_name TEXT,
    user_email TEXT,
    category TEXT,
    subject TEXT,
    description TEXT,
    status TEXT DEFAULT 'open',
    discord_message_id TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Ticket Replies Table
CREATE TABLE IF NOT EXISTS ticket_replies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id TEXT REFERENCES tickets (ticket_number) ON DELETE CASCADE,
    author_type TEXT,
    author_name TEXT,
    message TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Visitor Stats
CREATE TABLE IF NOT EXISTS visitors (
    ip TEXT PRIMARY KEY,
    user_agent TEXT,
    first_visit TIMESTAMPTZ DEFAULT NOW(),
    last_visit TIMESTAMPTZ DEFAULT NOW(),
    visit_count INT DEFAULT 1
);

CREATE TABLE IF NOT EXISTS license_keys (
  id bigserial primary key,
  transaction_id text references payments(transaction_id),
  key_value text,
  status text default 'active',
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Create the admin_credentials table
CREATE TABLE IF NOT EXISTS admin_credentials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password TEXT NOT NULL
);

-- Insert your admin password
-- Replace 'your_password_here' with the actual password you want to use
INSERT INTO admin_credentials (password) VALUES ('Zanpongos88!@');

-- Create a table to store OTP verification codes
create table public.verification_codes (
  email text primary key,
  code text not null,
  expires_at timestamp with time zone not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS) - Optional but recommended
alter table public.verification_codes enable row level security;

-- Create a policy that allows the service role (backend) to do everything
-- We (the backend) will be accessing this, so we need full access.
create policy "Enable all access for service role" on public.verification_codes for all using (true)
with
    check (true);

-- Create a table to store OTP verification codes
create table public.verification_codes (
  email text primary key,
  code text not null,
  expires_at timestamp with time zone not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS) - Optional but recommended
alter table public.verification_codes enable row level security;

-- Create a policy that allows the service role (backend) to do everything
-- We (the backend) will be accessing this, so we need full access.
create policy "Enable all access for service role" on public.verification_codes for all using (true)
with
    check (true);

-- User Reviews Table
CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT,
    display_name TEXT,
    rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
    game TEXT,
    content TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all access for service role" ON public.reviews FOR ALL USING (true)
WITH CHECK (true);

-- Script Metadata Table
CREATE TABLE IF NOT EXISTS script_metadata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    script_name TEXT UNIQUE NOT NULL,
    description TEXT,
    features TEXT[],
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for script_metadata
ALTER TABLE public.script_metadata ENABLE ROW LEVEL SECURITY;

-- Policy for service role access
CREATE POLICY "Enable all access for service role" ON public.script_metadata FOR ALL USING (true)
WITH
    CHECK (true);

-- Migration: Add game_selection column to payments
-- Run this in your Supabase SQL editor if the column doesn't already exist
ALTER TABLE payments ADD COLUMN IF NOT EXISTS game_selection TEXT[] DEFAULT NULL;
